import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import {Nunito} from 'next/font/google'

const MyAppFont = Nunito({subsets:['latin']})



export const metadata: Metadata = {
  title: "বইয়ের বিদ্বান",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={MyAppFont.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
